What if one fails?

diff --git a/.github/workflows/dockerimage.yml b/.github/workflows/dockerimage.yml
--- a/.github/workflows/dockerimage.yml
+++ b/.github/workflows/dockerimage.yml
@@ -85,7 +85,7 @@ jobs:
       - name: Run the docker image
         run: docker-compose up -d
       - name: Taking some sleep (for containers to come up)
-        run: sleep 45
+        run: sleep 10
       - name: Check if all containers are running
         run: docker ps
       - name: Dumping the logs
@@ -96,8 +96,6 @@ jobs:
  #       run: sleep 20
  #     - name: Database Check
  #       run: docker-compose exec -T php bin/console doctrine:schema:validate
-      - name: Unit  Check
-        run: docker-compose exec -T php bin/phpunit
 #      - uses: codecov/codecov-action@v1
 #        with:
 #            token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
@@ -113,12 +111,7 @@ jobs:
       # with:
       #     name: coverage.xml
       #     path: api/unit-coverage.xml  
-#      - name: Run Fossa checks
-#        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
-#        with:
-#            api-key: ${{secrets.fossaApiKey}}
-#            container: php
-#            debug: true
+
       # Postman      
 #      - name: Install postman dependencies
 #        run: npm install -g openapi-to-postmanv2
@@ -146,63 +139,6 @@ jobs:
           echo 'IMAGES=$images' >> $GITHUB_ENV
       - name: Show all images
         run: docker images
-      - name: Login to Container Registry
-        id: containerregistry-login
-        run: |
-         if [ "${{ secrets.GITHUB_TOKEN }}" != "" ]; then
-           echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $(cut -d'/' -f1 <<< $GITHUB_REPOSITORY) --password-stdin
-           echo "##[set-output name=success;]true"
-         else
-           echo "##[set-output name=success;]false"
-         fi
-      - if: steps.containerregistry-login.outputs.success == 'true' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/development' || github.ref == 'refs/heads/feature-soap' || github.ref == 'refs/heads/feature-soap-extra' || github.ref == 'refs/heads/feature-cleanup')
-        name: Push to Container Registry
-        run: docker-compose push
-
-      - if: steps.containerregistry-login.outputs.success == 'true' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/development' || github.ref == 'refs/heads/feature-soap' || github.ref == 'refs/heads/feature-soap-extra' || github.ref == 'refs/heads/feature-cleanup')
-        name: Push versioned containers to Container Registry
-        run: |
-          images=$(docker-compose images -q | xargs docker inspect --format='{{ index .RepoTags 0}}' | cut -d':' -f1 | grep $APP_NAME)
-          for image in $images
-          do
-            docker push "${image}":"${APP_BUILD}"
-          done
-      - name: Create kube config
-        id: kubeconfig
-        if: contains( github.ref, 'development' )
-        run: |
-          if [ "${{ secrets.KUBECONFIG }}" != "" ]; then
-            printf "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
-            echo "##[set-output name=success]true"
-          else
-            echo "##[set-output name=success]false"
-          fi
-      #            - name: Export release code
-      #              if: (success() || failure())
-      #              id: releasecode
-      #              run: |
-      #                  export RELEASE=$APP_BUILD-$(git rev-parse --short $GITHUB_SHA)
-      #                  echo "##[set-output name=releasename]$RELEASE"
-      - name: Print release name
-        if: (success() || failure())
-        run: echo $RELEASENAME
-        env:
-          RELEASENAME: ${{ steps.releasecode.outputs.releasename }}
-      - name: Create Release
-        if: contains( github.ref, 'master' ) && steps.kubeconfig.outputs.success == 'true' && ( success() || failure() )
-        id: create_release
-        uses: actions/create-release@v1
-        continue-on-error: true
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
-        with:
-          tag_name: ${{ steps.releasecode.outputs.releasename }}
-          release_name: ${{ steps.releasecode.outputs.releasename }}
-          draft: false
-          prerelease: false
-      - name: Chores
-        if: (success() || failure())
-        run: docker-compose down
   Trivy:
       needs: build
       runs-on: ubuntu-latest
@@ -211,7 +147,7 @@ jobs:
           - uses: actions/setup-node@v1
             with:
                 node-version: '16'
-          - name: Up the images images
+          - name: Up the images 
             run: docker compose up
           - name: Run Trivy to check for vulnerabilities
             uses: aquasecurity/trivy-action@master
@@ -229,7 +165,7 @@ jobs:
           - uses: actions/setup-node@v1
             with:
                 node-version: '16'
-          - name: Up the images images
+          - name: Up the images 
             run: docker compose up
           - name: Run Gryphe to check for vulnerabilities
             uses: anchore/scan-action@v3
@@ -246,13 +182,13 @@ jobs:
           - uses: actions/setup-node@v1
             with:
                 node-version: '16'
-          - name: Up the images images
+          - name: Up the images 
             run: docker compose up
           - name: Run Core Postman checks
             uses: matt-ball/newman-action@master
             with:
                 collection: api/postman.json
-  Dependency:
+  Dependencies:
       needs: build
       runs-on: ubuntu-latest
       steps:
@@ -260,18 +196,105 @@ jobs:
           - uses: actions/setup-node@v1
             with:
                 node-version: '16'
-          - name: Up the images images
+          - name: Up the images 
             run: docker compose up
           - name: Checksing al dependencies for known security issues
             run: |
                 curl -L -sS --output local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/download/v1.0.0/local-php-security-checker_1.0.0_linux_amd64
                 chmod +x ./local-php-security-checker
                 ./local-php-security-checker --path ./api/composer.lock
+  Unit:
+      needs: build
+      runs-on: ubuntu-latest
+      steps:
+          - uses: actions/checkout@v1
+          - uses: actions/setup-node@v1
+            with:
+                node-version: '16'
+          - name: Up the images
+            run: docker compose up
+          - name: Unit  Check
+            run: docker-compose exec -T php bin/phpunit
+  Fossa:
+      needs: build
+      runs-on: ubuntu-latest
+      steps:
+          - uses: actions/checkout@v1
+          - uses: actions/setup-node@v1
+            with:
+                node-version: '16'
+          - name: Up the images
+            run: docker compose up
+          - name: Run Fossa checks
+            uses: fossas/fossa-action@main # Use a specific version if locking is preferred
+            with:
+                api-key: ${{secrets.fossaApiKey}}
+                container: php
+                debug: true
   publish:
-      needs: [Trivy, Gryphe, Postman, Dependency]
+      needs: [Trivy, Gryphe, Postman, Dependencies, Unit]
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v1
         - uses: actions/setup-node@v1
           with:
             node-version: '16'
+        - name: Up the images
+          run: docker compose up
+        - name: Login to Container Registry
+          id: containerregistry-login
+          run: |
+              if [ "${{ secrets.GITHUB_TOKEN }}" != "" ]; then
+                echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $(cut -d'/' -f1 <<< $GITHUB_REPOSITORY) --password-stdin
+                echo "##[set-output name=success;]true"
+              else
+                echo "##[set-output name=success;]false"
+              fi
+        - if: steps.containerregistry-login.outputs.success == 'true' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/development' || github.ref == 'refs/heads/feature-soap' || github.ref == 'refs/heads/feature-soap-extra' || github.ref == 'refs/heads/feature-cleanup')
+          name: Push to Container Registry
+          run: docker-compose push
+
+        - if: steps.containerregistry-login.outputs.success == 'true' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/development' || github.ref == 'refs/heads/feature-soap' || github.ref == 'refs/heads/feature-soap-extra' || github.ref == 'refs/heads/feature-cleanup')
+          name: Push versioned containers to Container Registry
+          run: |
+              images=$(docker-compose images -q | xargs docker inspect --format='{{ index .RepoTags 0}}' | cut -d':' -f1 | grep $APP_NAME)
+              for image in $images
+              do
+                docker push "${image}":"${APP_BUILD}"
+              done
+        - name: Create kube config
+          id: kubeconfig
+          if: contains( github.ref, 'development' )
+          run: |
+              if [ "${{ secrets.KUBECONFIG }}" != "" ]; then
+                printf "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
+                echo "##[set-output name=success]true"
+              else
+                echo "##[set-output name=success]false"
+              fi
+          #            - name: Export release code
+          #              if: (success() || failure())
+          #              id: releasecode
+          #              run: |
+          #                  export RELEASE=$APP_BUILD-$(git rev-parse --short $GITHUB_SHA)
+          #                  echo "##[set-output name=releasename]$RELEASE"
+        - name: Print release name
+          if: (success() || failure())
+          run: echo $RELEASENAME
+          env:
+              RELEASENAME: ${{ steps.releasecode.outputs.releasename }}
+        - name: Create Release
+          if: contains( github.ref, 'master' ) && steps.kubeconfig.outputs.success == 'true' && ( success() || failure() )
+          id: create_release
+          uses: actions/create-release@v1
+          continue-on-error: true
+          env:
+              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
+          with:
+              tag_name: ${{ steps.releasecode.outputs.releasename }}
+              release_name: ${{ steps.releasecode.outputs.releasename }}
+              draft: false
+              prerelease: false
+        - name: Chores
+          if: (success() || failure())
+          run: docker-compose down
